// <auto-generated />
using System;
using JobCandidateHub.Persistence.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace JobCandidateHub.Persistence.Data.Migrations
{
    [DbContext(typeof(CandidateHubDBContext))]
    partial class CandidateHubDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("JobCandidateHub.Core.Entities.Candidate", b =>
                {
                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<TimeSpan?>("BestCallTime")
                        .HasColumnType("interval")
                        .HasColumnName("best_call_time");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("comment");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<string>("GitHubProfileUrl")
                        .HasColumnType("text")
                        .HasColumnName("git_hub_profile_url");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.Property<string>("LinkedInProfileUrl")
                        .HasColumnType("text")
                        .HasColumnName("linked_in_profile_url");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.HasKey("Email")
                        .HasName("pk_candidates");

                    b.ToTable("candidates", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
